name: Coverity CI

# We only want to test official release code, not every pull request.
on:
  push:
    branches: [action]


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: .github/build.sh coverity
    - uses: vapier/coverity-scan-action@v0
      with:
        project: frankmorgner%2Fopenpace
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
