name: Ubuntu CI

on:
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - '**.i'
      - '**.in'
      - '**.sh'
      - '**.py'
      - '**.go'
      - '**.java'
      - '**.rb'
      - .github/workflows/ubuntu.yml
  push:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: .github/build-ubuntu.sh
    - uses: actions/upload-artifact@v2
      with:
        name: openpace
        path:
          openpace*.tar.gz

  build-mingw-64:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: .github/build-ubuntu-mingw-64.sh
    - uses: actions/upload-artifact@v2
      with:
        name: openpace-win64
        path:
          openpace*_win32

  build-mingw-32:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: .github/build-ubuntu-mingw-32.sh
    - uses: actions/upload-artifact@v2
      with:
        name: openpace-win32
        path:
          openpace*_win32
